/* empty css                      */(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const d of t.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();document.querySelectorAll(".faq-acc-el-trigger").forEach(c=>{c.addEventListener("click",()=>{const o=c.closest(".faq-acc-el"),r=o.querySelector(".faq-acc-el-descr-frame");o.classList.contains("open")?(o.classList.remove("open"),r.style.maxHeight="0"):(o.classList.add("open"),r.style.maxHeight=r.scrollHeight+"px")})});document.addEventListener("DOMContentLoaded",()=>{const c=document.querySelector(".menu-button"),o=c.querySelector(".icon"),r=document.querySelector(".modal"),a=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const d=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M5 6H19M5 18H19M5 12H19" stroke="#CECED1" stroke-linecap="round" />
</svg>
    `,n=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M5.25 5.25L12 12M12 12L5.25 18.75M12 12L18.75 18.75M12 12L18.75 5.25" stroke="#CECED1" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `;c.addEventListener("click",()=>{t=!t,o.innerHTML=t?n:d,t?s():i()}),a.forEach(u=>u.addEventListener("click",()=>{i(),o.innerHTML=d,t=!1})),window.addEventListener("scroll",l);function s(){r.style.display="block"}function i(){r.style.display="none"}function l(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function c(){const n=document.getElementById("site-header");return n?n.offsetHeight:0}function o(n){const s=document.getElementById(n);if(!s)return;const i=c(),l=s.getBoundingClientRect().top+window.pageYOffset-i;window.scrollTo({top:l,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(n=>{n.addEventListener("click",function(s){const i=this.getAttribute("href");if(!i)return;const[l,u]=i.split("#");if(!u)return;const f=window.location.pathname.split("/").pop();!(l===""||l==="./"||l===f||l==="./"+f)||!document.getElementById(u)||(s.preventDefault(),o(u),t(u))})});const a=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(n){e.forEach(i=>i.classList.remove("active"));const s=document.querySelector(`.navigation-item a[href*="#${n}"]`);s&&s.closest(".navigation-item").classList.add("active")}function d(){const n=window.pageYOffset+c()+100;a.forEach(s=>{const i=s.offsetTop,l=i+s.offsetHeight;n>=i&&n<l&&t(s.id)})}if(window.addEventListener("scroll",d),window.location.hash){const n=window.location.hash.substring(1);setTimeout(()=>{o(n),t(n)},300)}});document.addEventListener("DOMContentLoaded",function(){const c=document.getElementById("cookie-popup"),o=document.getElementById("accept-cookies"),r=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(c.style.display="block"),o.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),c.style.display="none"}),r.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),c.style.display="none"})});
//# sourceMappingURL=index.js.map
